### ISSUE TITLE
Not working -- Help :)

### ISSUE THREAD

**Issue by christianreiss** [voxpupuli/hiera-eyaml#165]
Hey, I am running Centos7 with...

```
puppetdb-2.3.5-1.el7.noarch
puppetlabs-release-7-11.noarch
puppet-3.8.1-1.el7.noarch
puppetdb-terminus-2.3.5-1.el7.noarch
puppetserver-1.1.1-1.el7.noarch
```

hiera.yaml:

```

---
:backends:
  - eyaml
  - yaml
:hierarchy:
  - nodes/%{::fqdn}
  - os/%{::operatingsystem}
  - os/%{::operatingsystem}/%{::lsbmajdistrelease}
  - domain/%{::domain}
  - common
:yaml:
  :datadir: '/etc/puppet/hiera'
:eyaml:
  :datadir: '/etc/puppet/hiera'
  :pkcs7_private_key: /etc/puppet-keys/private_key.pkcs7.pem
  :pkcs7_public_key:  /etc/puppet-keys/public_key.pkcs7.pem
:logger: "puppet"
```

A normal puppet run without any encryption does work. If there is some sort of encryption I seee these errors in puppetserver.log:

```
/usr/share/ruby/vendor_ruby/puppet/parser/functions/fail.rb:3:in `real_function_fail'
/usr/share/ruby/vendor_ruby/puppet/parser/functions.rb:164:in `function_fail'
/usr/share/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/usr/share/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/usr/share/ruby/vendor_ruby/puppet/parser/functions.rb:157:in `function_fail'
/usr/share/ruby/vendor_ruby/puppet/parser/ast/function.rb:42:in `evaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast.rb:61:in `safeevaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:11:in `evaluate'
org/jruby/RubyArray.java:1613:in `each'
/usr/share/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:10:in `evaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast.rb:61:in `safeevaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast/ifstatement.rb:25:in `evaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast.rb:61:in `safeevaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:11:in `evaluate'
org/jruby/RubyArray.java:1613:in `each'
/usr/share/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:10:in `evaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast.rb:61:in `safeevaluate'
/usr/share/ruby/vendor_ruby/puppet/resource/type.rb:127:in `evaluate_code'
/usr/share/ruby/vendor_ruby/puppet/parser/resource.rb:79:in `evaluate'
org/jruby/RubyArray.java:1613:in `each'
/usr/share/ruby/vendor_ruby/puppet/parser/compiler.rb:236:in `evaluate_classes'
/usr/share/ruby/vendor_ruby/puppet/parser/functions/include.rb:33:in `real_function_include'
/usr/share/ruby/vendor_ruby/puppet/parser/functions.rb:164:in `function_include'
/usr/share/ruby/vendor_ruby/puppet/util/profiler/around_profiler.rb:58:in `profile'
/usr/share/ruby/vendor_ruby/puppet/util/profiler.rb:51:in `profile'
/usr/share/ruby/vendor_ruby/puppet/parser/functions.rb:157:in `function_include'
/usr/share/ruby/vendor_ruby/puppet/parser/ast/function.rb:42:in `evaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast.rb:61:in `safeevaluate'
/usr/share/ruby/vendor_ruby/puppet/parser/ast/block_expression.rb:11:in `evaluate'
```

I did the installation according to the instructions.

**Comment by TomPoulton** [comment]
There's nothing in that stacktrace that points to eyaml specifically, I'm not trying to pass the buck, but I'm not that familiar with puppet server yet so I don't recognize that stack trace.

It's interesting that it works when there's no encryption but fails when there is. What's the difference between an encrypted run and a normal run, do you copy different hiere files and test with the same node, use a different node, comment out a variable/template/function call?

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
