### ISSUE TITLE
ArgumentError

### ISSUE THREAD

**Issue by DevOpsCow** [voxpupuli/hiera-eyaml#193]
I guess this is related to the YAML or Ruby version, but I could not find any requirements on the readme file.

Versions:
OS: Ubuntu 12.04.5 LTS
Ruby 1.8.7 (2011-06-30 patchlevel 352) [x86_64-linux]  - as it comes with the OS
Hiera 1.3.4-1puppetlabs1 - part of Puppet 3.8.6 installation
hiera-eyaml (2.1.0)

I'm able to:
- edit eyaml files properly with `eyaml edit myfile.eyaml` and read/edit the (decrypted) text values
- cat the file and confirm there is an encryption block (e.g.: no plain text values)
- run `eyaml decrypt -f hieradata/secure.eyaml` and return the decrypted text values

But when I do a `hiera ehiera_string` or `hiera plain_string`  I receive this error:

```
/usr/lib/ruby/1.8/yaml.rb:133:in 'load': syntax error on line 4, col 0: '       DQYJKoZIhvcNAQEBBQAEggEAeNg0dQMExp5MYhblkKiaE1i8EMLZf/W+IolJ' (ArgumentError)
        from /usr/lib/ruby/1.8/yaml.rb:133:in 'load'
        from /var/lib/gems/1.8/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml_backend.rb:36:in 'lookup'
        from /usr/lib/ruby/vendor_ruby/hiera/filecache.rb:53:in 'read_file'
        from /usr/lib/ruby/vendor_ruby/hiera/filecache.rb:28:in 'read'
        from /var/lib/gems/1.8/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml_backend.rb:35:in 'lookup'
        from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:76:in 'datasources'
        from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:74:in 'map'
        from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:74:in 'datasources'
        from /var/lib/gems/1.8/gems/hiera-eyaml-2.1.0/lib/hiera/backend/eyaml_backend.rb:29:in 'lookup'
        from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:206:in 'lookup'
        from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:203:in 'each'
        from /usr/lib/ruby/vendor_ruby/hiera/backend.rb:203:in 'lookup'
        from /usr/lib/ruby/vendor_ruby/hiera.rb:60:in 'lookup'
        from /usr/bin/hiera:225
```

my secure.eyaml file:

```

---
plain_string: 'This is plain text in secure.eyaml'
ehiera_string: >
        ENC[PKCS7,MIIBiQYJKoZIhvcNAQcDoIIBejCCAXYCAQAxggEhMIIBHQIBADAFMAACAQEw
        DQYJKoZIhvcNAQEBBQAEggEAeNg0dQMExp5MYhblkKiaE1i8EMLZf/W+IolJ
        rZ9DjRzAmE9H6X8iQS3OZVo9Im2JGtEhtkVgrF6uyWxFxeCwcyN4oc2rteBk
        ZIXILZ6OuDmVCNK8rVuZVeae5jCdUpbv+wcJpvW1L3arNKDFDXlcY49XWcYr
        0LwcPaGW0r017YC0bGeEjbHXZZMQYxpVnaVPiuv2a/0obqoYBNNDaiELYRI5
        alaMNYqmEzXLb++gA3VzVWPGA+PNiIkO2fiqJg2cgy4tUS9Y8Hio29p/bvr7
        pePhFWGj5PmasK3vN7bfHS3VemcCVz++5GXObvtp5ajk9lnHpK4U/rTQiEAo
        VMldjzBMBgkqhkiG9w0BBwEwHQYJYIZIAWUDBAEqBBAqNzMY6VFRjite1New
        x6uTgCCYLcU5Bz5jWb0WvdFIjxJj591dB+MqznEcqk98+wBCxg==]
```

Example of decryption working:

```
# eyaml decrypt -f hieradata/secure.eyaml
[hiera-eyaml-core] Loaded config from /etc/eyaml/config.yaml
[hiera-eyaml-core] Loaded config from /root/.eyaml/config.yaml

---
plain_string: 'This is plain text in secure.eyaml'
ehiera_string: This is encripted

```

If this is because of the Ruby/YAML version I'm running, please let me know the required versions.
Thanks!

**Comment by Dan33l** [comment]
it can be reopened if it's reproducible on the latest Puppet 4 or newer
